// The single source of truth for what a backup carries — and, just as
// importantly, what it deliberately does not.
//
// WHY THIS FILE EXISTS
// Backup/import is a hand-typed mirror of the schema in three places
// (ImportBundle, buildImportPayload, and the import_replace_account RPC). Every
// migration that adds a table or a column silently desynchronises all three, and
// nothing failed when it happened: `tsc` passed, the unit suite passed, and the
// SQL test passed, because the suite's "every NOT NULL column" check was driven
// by a hand-written map that encoded the very assumption the bug came from.
//
// Six whole tables and eight user_settings columns went missing that way. The
// worst of them, work_schedules, is the denominator the efficiency engine
// divides by — so migrating an account silently changed the tech's numbers.
//
// HOW THIS FILE PREVENTS THE NEXT ONE
// The manifest is keyed by the GENERATED database types, using mapped types that
// require an entry for every table and, on a carried table, every column. So:
//
//   * add a table    -> BACKUP_MANIFEST is missing a key -> tsc fails
//   * add a column   -> that table's `columns` is missing a key -> tsc fails
//
// You cannot merge a migration without saying, in writing, whether the new field
// belongs in a backup. Saying "no" is a perfectly good answer — it just has to be
// a decision with a reason attached, not an oversight.
//
// The type check proves the manifest describes the schema. `backup-manifest.test.ts`
// proves the CODE matches the manifest, which is the other half: a column marked
// `carry` here that buildImportPayload forgets is still a silent loss.
//
// STALE-TYPES CAVEAT
// database.types.ts is regenerated by hand (`npx supabase gen types`). If someone
// writes a migration and skips the regen, the types don't know about the new
// column and this check passes on a lie. The migrate skill closes that hole by
// regenerating and failing if the file comes back dirty.

import type { Database } from "@/lib/supabase/database.types";

type Tables = Database["public"]["Tables"];
export type TableName = keyof Tables;
type ColumnsOf<T extends TableName> = keyof Tables[T]["Row"];

/**
 * Why a column doesn't travel. Every value here is a decision someone made, not
 * a default — an omitted column reads as NULL on import, never as its default.
 */
export type ColumnDisposition =
  /** Written to the destination account from the backup file. */
  | "carry"
  /**
   * Present in the payload, but the RPC decides its value — never the file.
   * user_id comes from auth.uid(), timestamps from now(). Accepting these from
   * user-supplied JSON is how a backup becomes a privilege-escalation vector.
   */
  | "server-controlled"
  /** Deliberately dropped. The string is the reason, and it is required. */
  | { exclude: string };

export type TableManifest<T extends TableName> =
  | {
      carried: false;
      /** Required. "We didn't get to it" is not a reason; say what it costs. */
      reason: string;
      /** True when the user should be TOLD, because real data stays behind. */
      warnUser?: boolean;
    }
  | {
      carried: true;
      /** Key under which this table's rows live in the backup JSON. */
      bundleKey: string;
      columns: { [C in ColumnsOf<T>]: ColumnDisposition };
    };

/**
 * Every table in the public schema. The mapped type makes this exhaustive —
 * a new table will not compile until it appears here.
 */
export const BACKUP_MANIFEST: { [T in TableName]: TableManifest<T> } = {
  // ---------------------------------------------------------------------
  // Carried — the account's own work
  // ---------------------------------------------------------------------
  user_settings: {
    carried: true,
    bundleKey: "settings",
    columns: {
      split_day: "carry",
      period_overrides: "carry",
      // The six that were silently dropped until 2026-08-12. share_labor_times
      // was the nastiest: it reverted to false on import, quietly un-enrolling a
      // True Time contributor without telling them.
      goal_hours: "carry",
      tag_colors: "carry",
      reference_hourly_rate: "carry",
      ro_template: "carry",
      default_labor_type: "carry",
      share_labor_times: "carry",
      // A backup is user-supplied JSON that a user can open in a text editor.
      // Carrying this would let anyone set "is_admin": true and import their way
      // to admin. The RPC must never read it from the payload.
      is_admin: { exclude: "privilege flag — a crafted backup must not grant it" },
      user_id: "server-controlled",
      updated_at: "server-controlled",
    },
  },

  op_codes: {
    carried: true,
    bundleKey: "opCodes",
    columns: {
      id: "carry",
      code: "carry",
      description: "carry",
      flag_hours: "carry",
      sort_order: "carry",
      notes: "carry",
      tags: "carry",
      created_at: "carry",
      user_id: "server-controlled",
    },
  },

  op_code_variants: {
    carried: true,
    bundleKey: "opCodes[].subOpCodes",
    columns: {
      id: "carry",
      op_code_id: "carry",
      code: "carry",
      description: "carry",
      flag_hours: "carry",
      sort_order: "carry",
      created_at: "carry",
      user_id: "server-controlled",
    },
  },

  entries: {
    carried: true,
    bundleKey: "entries",
    columns: {
      id: "carry",
      date: "carry",
      ro_number: "carry",
      vehicle_year: "carry",
      vehicle_make: "carry",
      vehicle_model: "carry",
      vehicle_vin: "carry",
      vehicle_mileage: "carry",
      flag_hours: "carry",
      notes: "carry",
      comeback_of_entry_id: "carry",
      comeback_kind: "carry",
      created_at: "carry",
      updated_at: "carry",
      user_id: "server-controlled",
    },
  },

  entry_op_codes: {
    carried: true,
    bundleKey: "entries[].opCodes",
    columns: {
      id: "carry",
      entry_id: "carry",
      op_code_id: "carry",
      sub_op_code_id: "carry",
      custom: "carry",
      custom_code: "carry",
      custom_description: "carry",
      flag_hours: "carry",
      actual_hours: "carry",
      // "Did the shop actually pay me for this?" — the worst of the original
      // silent losses.
      paid_hours: "carry",
      is_comeback: "carry",
      labor_type: "carry",
      notes: "carry",
      position: "carry",
    },
  },

  bonuses: {
    carried: true,
    bundleKey: "bonuses",
    columns: {
      id: "carry",
      date: "carry",
      amount: "carry",
      category: "carry",
      source: "carry",
      note: "carry",
      entry_id: "carry",
      created_at: "carry",
      updated_at: "carry",
      user_id: "server-controlled",
    },
  },

  daily_clock_hours: {
    carried: true,
    bundleKey: "dailyClocks",
    columns: { date: "carry", hours: "carry", user_id: "server-controlled" },
  },

  paid_period_hours: {
    carried: true,
    bundleKey: "paidPeriods",
    columns: { period_key: "carry", paid_flag_hours: "carry", user_id: "server-controlled" },
  },

  labor_rates: {
    carried: true,
    bundleKey: "laborRates",
    columns: {
      id: "carry",
      // Without these every dollar figure in the app reads $0 on the new
      // account until they're re-entered by hand.
      hourly_rate: "carry",
      labor_type: "carry",
      created_at: "carry",
      updated_at: "carry",
      user_id: "server-controlled",
    },
  },

  disputes: {
    carried: true,
    bundleKey: "disputes",
    columns: {
      id: "carry",
      period_key: "carry",
      period_label: "carry",
      scope: "carry",
      status: "carry",
      // Frozen at generation and never recomputed — recomputing would shrink the
      // claim to zero the moment the shop paid, destroying the record of what was
      // asked for. So these must survive a migration verbatim.
      claimed_hours: "carry",
      claimed_dollars: "carry",
      recovered_hours: "carry",
      recovered_dollars: "carry",
      note: "carry",
      generated_at: "carry",
      submitted_at: "carry",
      answered_at: "carry",
      resolved_at: "carry",
      created_at: "carry",
      updated_at: "carry",
      user_id: "server-controlled",
    },
  },

  dispute_lines: {
    carried: true,
    bundleKey: "disputes[].lines",
    columns: {
      id: "carry",
      dispute_id: "carry",
      // A dispute is a frozen claim built to outlive its RO, so a null entry_id
      // or line_id is a supported state here, not corruption.
      entry_id: "carry",
      line_id: "carry",
      ro_number: "carry",
      work_date: "carry",
      code: "carry",
      description: "carry",
      flagged_hours: "carry",
      paid_hours: "carry",
      claimed_hours: "carry",
      claimed_dollars: "carry",
      recovered_hours: "carry",
      recovered_dollars: "carry",
      had_photo: "carry",
      position: "carry",
      created_at: "carry",
      updated_at: "carry",
      user_id: "server-controlled",
    },
  },

  unpaid_time: {
    carried: true,
    bundleKey: "unpaidTime",
    columns: {
      id: "carry",
      date: "carry",
      kind: "carry",
      hours: "carry",
      note: "carry",
      source: "carry",
      entry_id: "carry",
      // The RO this rework traces back to. Remapped like any other entry
      // reference; an out-of-bundle target becomes null rather than pointing at
      // a stranger's record.
      original_entry_id: "carry",
      created_at: "carry",
      updated_at: "carry",
      user_id: "server-controlled",
    },
  },

  // ---------------------------------------------------------------------
  // Carried as of v3 — the Schedule and Career features, absent from every
  // backup written before 2026-08-12.
  // ---------------------------------------------------------------------
  work_schedules: {
    carried: true,
    bundleKey: "workSchedules",
    columns: {
      id: "carry",
      // The efficiency engine divides by these. Losing them doesn't blank the
      // numbers, it CHANGES them — the failure a tech is least likely to catch.
      //
      // The schedule is a rotation, not a weekday map: `weeks` holds the shift
      // pattern, `rotation_weeks` its length, and `anchor_monday` the date the
      // cycle is counted from. All three have to travel together or the rotation
      // lands out of phase and every scheduled hour after the anchor is wrong.
      effective_from: "carry",
      anchor_monday: "carry",
      rotation_weeks: "carry",
      weeks: "carry",
      created_at: "carry",
      user_id: "server-controlled",
    },
  },

  days_off: {
    carried: true,
    bundleKey: "daysOff",
    columns: {
      id: "carry",
      // A range, not a single date — a week of vacation is one row.
      start_date: "carry",
      end_date: "carry",
      created_at: "carry",
      user_id: "server-controlled",
    },
  },

  work_shift_overrides: {
    carried: true,
    bundleKey: "shiftOverrides",
    columns: {
      date: "carry",
      shift: "carry",
      // Bookkeeping only — the override IS the date/shift pair. The read layer
      // returns a date→shift map and never surfaces this, so stamping it fresh
      // loses nothing a user could observe.
      created_at: "server-controlled",
      user_id: "server-controlled",
    },
  },

  confirmed_zero_days: {
    carried: true,
    bundleKey: "confirmedZeroDays",
    columns: {
      date: "carry",
      // As above: the read layer returns bare dates.
      created_at: "server-controlled",
      user_id: "server-controlled",
    },
  },

  portfolio_snapshots: {
    carried: true,
    bundleKey: "portfolioSnapshots",
    columns: {
      id: "carry",
      seq: "carry",
      ro_threshold: "carry",
      stats: "carry",
      created_at: "carry",
      user_id: "server-controlled",
    },
  },

  career_milestones: {
    carried: true,
    bundleKey: "careerMilestones",
    columns: {
      threshold: "carry",
      achieved_at: "carry",
      user_id: "server-controlled",
    },
  },

  // ---------------------------------------------------------------------
  // Not carried. Each of these is a decision; `warnUser` marks the ones where
  // real data stays behind and the user deserves to hear about it up front.
  // ---------------------------------------------------------------------
  entry_photos: {
    carried: false,
    warnUser: true,
    reason:
      "The image binaries live in the private ro-photos bucket, not in the JSON. " +
      "Carrying the metadata alone would create rows pointing at storage objects " +
      "that don't exist on the new account — broken tiles instead of photos.",
  },

  labor_time_observations: {
    carried: false,
    warnUser: true,
    reason:
      "True Time contributions. Import only ever touches the importing user's own " +
      "rows, so the source account keeps its observations in the pool; copying them " +
      "would count the same real-world jobs twice and skew the shared medians.",
  },

  active_timers: {
    carried: false,
    reason: "Transient — a timer running on the old account means nothing on the new one.",
  },

  labor_time_aggregates: {
    carried: false,
    reason: "Derived. Rebuilt by the refresh function from observations across all users.",
  },

  bug_reports: {
    carried: false,
    reason: "Support tickets, not account data. They stay with the account that filed them.",
  },

  bug_report_photos: {
    carried: false,
    reason: "Attachments on support tickets; binaries live in storage. See bug_reports.",
  },

  client_errors: {
    carried: false,
    reason: "Telemetry written by the app for debugging; carries no user-authored data.",
  },
};

/** Tables whose absence the import preflight should tell the user about. */
export function tablesUserShouldBeWarnedAbout(): { table: TableName; reason: string }[] {
  return (Object.entries(BACKUP_MANIFEST) as [TableName, TableManifest<TableName>][])
    .filter(([, m]) => !m.carried && m.warnUser)
    .map(([table, m]) => ({ table, reason: (m as { reason: string }).reason }));
}

/** Column names of a carried table that must appear in the import payload. */
export function carriedColumns(table: TableName): string[] {
  const m = BACKUP_MANIFEST[table];
  if (!m.carried) return [];
  return Object.entries(m.columns)
    .filter(([, d]) => d === "carry")
    .map(([c]) => c);
}
