// Auto-generated by `npx supabase gen types typescript --local`.
// Regenerate after every migration — do not hand-edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      daily_clock_hours: {
        Row: {
          date: string
          hours: number
          user_id: string
        }
        Insert: {
          date: string
          hours?: number
          user_id: string
        }
        Update: {
          date?: string
          hours?: number
          user_id?: string
        }
        Relationships: []
      }
      entries: {
        Row: {
          created_at: string
          date: string
          flag_hours: number
          id: string
          notes: string
          ro_number: string
          updated_at: string
          user_id: string
          vehicle_make: string
          vehicle_model: string
          vehicle_vin: string
          vehicle_year: string
        }
        Insert: {
          created_at?: string
          date: string
          flag_hours?: number
          id?: string
          notes?: string
          ro_number: string
          updated_at?: string
          user_id: string
          vehicle_make?: string
          vehicle_model?: string
          vehicle_vin?: string
          vehicle_year?: string
        }
        Update: {
          created_at?: string
          date?: string
          flag_hours?: number
          id?: string
          notes?: string
          ro_number?: string
          updated_at?: string
          user_id?: string
          vehicle_make?: string
          vehicle_model?: string
          vehicle_vin?: string
          vehicle_year?: string
        }
        Relationships: []
      }
      entry_op_codes: {
        Row: {
          actual_hours: number | null
          custom: boolean
          custom_code: string | null
          custom_description: string | null
          entry_id: string
          flag_hours: number
          id: string
          op_code_id: string | null
          position: number
        }
        Insert: {
          actual_hours?: number | null
          custom?: boolean
          custom_code?: string | null
          custom_description?: string | null
          entry_id: string
          flag_hours?: number
          id?: string
          op_code_id?: string | null
          position?: number
        }
        Update: {
          actual_hours?: number | null
          custom?: boolean
          custom_code?: string | null
          custom_description?: string | null
          entry_id?: string
          flag_hours?: number
          id?: string
          op_code_id?: string | null
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: "entry_op_codes_entry_id_fkey"
            columns: ["entry_id"]
            isOneToOne: false
            referencedRelation: "entries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entry_op_codes_op_code_id_fkey"
            columns: ["op_code_id"]
            isOneToOne: false
            referencedRelation: "op_codes"
            referencedColumns: ["id"]
          },
        ]
      }
      op_codes: {
        Row: {
          code: string
          created_at: string
          description: string
          flag_hours: number
          id: string
          sort_order: number
          user_id: string
        }
        Insert: {
          code: string
          created_at?: string
          description?: string
          flag_hours?: number
          id?: string
          sort_order?: number
          user_id: string
        }
        Update: {
          code?: string
          created_at?: string
          description?: string
          flag_hours?: number
          id?: string
          sort_order?: number
          user_id?: string
        }
        Relationships: []
      }
      paid_period_hours: {
        Row: {
          paid_flag_hours: number
          period_key: string
          user_id: string
        }
        Insert: {
          paid_flag_hours?: number
          period_key: string
          user_id: string
        }
        Update: {
          paid_flag_hours?: number
          period_key?: string
          user_id?: string
        }
        Relationships: []
      }
      user_settings: {
        Row: {
          period_overrides: Json
          ro_template: Json | null
          split_day: number
          timer_accumulated: number
          timer_ro_id: string | null
          timer_start_time: number | null
          updated_at: string
          user_id: string
        }
        Insert: {
          period_overrides?: Json
          ro_template?: Json | null
          split_day?: number
          timer_accumulated?: number
          timer_ro_id?: string | null
          timer_start_time?: number | null
          updated_at?: string
          user_id: string
        }
        Update: {
          period_overrides?: Json
          ro_template?: Json | null
          split_day?: number
          timer_accumulated?: number
          timer_ro_id?: string | null
          timer_start_time?: number | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const

