// Auto-generated by `npx supabase gen types typescript --local`.
// Regenerate after every migration — do not hand-edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      client_errors: {
        Row: {
          created_at: string
          id: string
          message: string
          stack_hash: string | null
          url: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          message: string
          stack_hash?: string | null
          url?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          message?: string
          stack_hash?: string | null
          url?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      bug_reports: {
        Row: {
          app_build: string | null
          category: string | null
          created_at: string
          description: string
          id: string
          page_url: string | null
          severity: string | null
          status: string
          triage_notes: string | null
          updated_at: string
          user_agent: string | null
          user_id: string
          viewport: string | null
        }
        Insert: {
          app_build?: string | null
          category?: string | null
          created_at?: string
          description: string
          id?: string
          page_url?: string | null
          severity?: string | null
          status?: string
          triage_notes?: string | null
          updated_at?: string
          user_agent?: string | null
          user_id: string
          viewport?: string | null
        }
        Update: {
          app_build?: string | null
          category?: string | null
          created_at?: string
          description?: string
          id?: string
          page_url?: string | null
          severity?: string | null
          status?: string
          triage_notes?: string | null
          updated_at?: string
          user_agent?: string | null
          user_id?: string
          viewport?: string | null
        }
        Relationships: []
      }
      bug_report_photos: {
        Row: {
          byte_size: number
          created_at: string
          id: string
          report_id: string
          storage_path: string
          user_id: string
        }
        Insert: {
          byte_size?: number
          created_at?: string
          id?: string
          report_id: string
          storage_path: string
          user_id: string
        }
        Update: {
          byte_size?: number
          created_at?: string
          id?: string
          report_id?: string
          storage_path?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bug_report_photos_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "bug_reports"
            referencedColumns: ["id"]
          },
        ]
      }
      bonuses: {
        Row: {
          amount: number
          category: string
          created_at: string
          date: string
          entry_id: string | null
          id: string
          note: string | null
          source: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          amount?: number
          category: string
          created_at?: string
          date: string
          entry_id?: string | null
          id?: string
          note?: string | null
          source?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          amount?: number
          category?: string
          created_at?: string
          date?: string
          entry_id?: string | null
          id?: string
          note?: string | null
          source?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bonuses_entry_id_fkey"
            columns: ["entry_id"]
            isOneToOne: false
            referencedRelation: "entries"
            referencedColumns: ["id"]
          },
        ]
      }
      career_milestones: {
        Row: {
          achieved_at: string
          threshold: number
          user_id: string
        }
        Insert: {
          achieved_at?: string
          threshold: number
          user_id: string
        }
        Update: {
          achieved_at?: string
          threshold?: number
          user_id?: string
        }
        Relationships: []
      }
      days_off: {
        Row: {
          created_at: string
          end_date: string
          id: string
          start_date: string
          user_id: string
        }
        Insert: {
          created_at?: string
          end_date: string
          id?: string
          start_date: string
          user_id: string
        }
        Update: {
          created_at?: string
          end_date?: string
          id?: string
          start_date?: string
          user_id?: string
        }
        Relationships: []
      }
      portfolio_snapshots: {
        Row: {
          created_at: string
          id: string
          ro_threshold: number
          seq: number
          stats: Json
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          ro_threshold: number
          seq: number
          stats: Json
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          ro_threshold?: number
          seq?: number
          stats?: Json
          user_id?: string
        }
        Relationships: []
      }
      daily_clock_hours: {
        Row: {
          date: string
          hours: number
          user_id: string
        }
        Insert: {
          date: string
          hours?: number
          user_id: string
        }
        Update: {
          date?: string
          hours?: number
          user_id?: string
        }
        Relationships: []
      }
      entries: {
        Row: {
          created_at: string
          date: string
          flag_hours: number
          id: string
          notes: string
          ro_number: string
          updated_at: string
          user_id: string
          vehicle_make: string
          vehicle_mileage: string
          vehicle_model: string
          vehicle_vin: string
          vehicle_year: string
        }
        Insert: {
          created_at?: string
          date: string
          flag_hours?: number
          id?: string
          notes?: string
          ro_number: string
          updated_at?: string
          user_id: string
          vehicle_make?: string
          vehicle_mileage?: string
          vehicle_model?: string
          vehicle_vin?: string
          vehicle_year?: string
        }
        Update: {
          created_at?: string
          date?: string
          flag_hours?: number
          id?: string
          notes?: string
          ro_number?: string
          updated_at?: string
          user_id?: string
          vehicle_make?: string
          vehicle_mileage?: string
          vehicle_model?: string
          vehicle_vin?: string
          vehicle_year?: string
        }
        Relationships: []
      }
      entry_op_codes: {
        Row: {
          actual_hours: number | null
          custom: boolean
          custom_code: string | null
          custom_description: string | null
          entry_id: string
          flag_hours: number
          id: string
          labor_type: string | null
          notes: string
          op_code_id: string | null
          paid_hours: number | null
          position: number
          sub_op_code_id: string | null
        }
        Insert: {
          actual_hours?: number | null
          custom?: boolean
          custom_code?: string | null
          custom_description?: string | null
          entry_id: string
          flag_hours?: number
          id?: string
          labor_type?: string | null
          notes?: string
          op_code_id?: string | null
          paid_hours?: number | null
          position?: number
          sub_op_code_id?: string | null
        }
        Update: {
          actual_hours?: number | null
          custom?: boolean
          custom_code?: string | null
          custom_description?: string | null
          entry_id?: string
          flag_hours?: number
          id?: string
          labor_type?: string | null
          notes?: string
          op_code_id?: string | null
          paid_hours?: number | null
          position?: number
          sub_op_code_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "entry_op_codes_entry_id_fkey"
            columns: ["entry_id"]
            isOneToOne: false
            referencedRelation: "entries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entry_op_codes_op_code_id_fkey"
            columns: ["op_code_id"]
            isOneToOne: false
            referencedRelation: "op_codes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entry_op_codes_sub_op_code_id_fkey"
            columns: ["sub_op_code_id"]
            isOneToOne: false
            referencedRelation: "op_code_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      entry_photos: {
        Row: {
          byte_size: number
          captured_at: string
          created_at: string
          entry_id: string
          id: string
          storage_path: string
          user_id: string
        }
        Insert: {
          byte_size?: number
          captured_at?: string
          created_at?: string
          entry_id: string
          id?: string
          storage_path: string
          user_id: string
        }
        Update: {
          byte_size?: number
          captured_at?: string
          created_at?: string
          entry_id?: string
          id?: string
          storage_path?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "entry_photos_entry_id_fkey"
            columns: ["entry_id"]
            isOneToOne: false
            referencedRelation: "entries"
            referencedColumns: ["id"]
          },
        ]
      }
      labor_rates: {
        Row: {
          created_at: string
          hourly_rate: number
          id: string
          labor_type: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          hourly_rate?: number
          id?: string
          labor_type: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          hourly_rate?: number
          id?: string
          labor_type?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      op_code_variants: {
        Row: {
          code: string
          created_at: string
          description: string
          flag_hours: number
          id: string
          op_code_id: string
          sort_order: number
          user_id: string
        }
        Insert: {
          code: string
          created_at?: string
          description?: string
          flag_hours?: number
          id?: string
          op_code_id: string
          sort_order?: number
          user_id: string
        }
        Update: {
          code?: string
          created_at?: string
          description?: string
          flag_hours?: number
          id?: string
          op_code_id?: string
          sort_order?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "op_code_variants_op_code_id_fkey"
            columns: ["op_code_id"]
            isOneToOne: false
            referencedRelation: "op_codes"
            referencedColumns: ["id"]
          },
        ]
      }
      op_codes: {
        Row: {
          code: string
          created_at: string
          description: string
          flag_hours: number
          id: string
          notes: string
          sort_order: number
          tags: string[]
          user_id: string
        }
        Insert: {
          code: string
          created_at?: string
          description?: string
          flag_hours?: number
          id?: string
          notes?: string
          sort_order?: number
          tags?: string[]
          user_id: string
        }
        Update: {
          code?: string
          created_at?: string
          description?: string
          flag_hours?: number
          id?: string
          notes?: string
          sort_order?: number
          tags?: string[]
          user_id?: string
        }
        Relationships: []
      }
      paid_period_hours: {
        Row: {
          paid_flag_hours: number
          period_key: string
          user_id: string
        }
        Insert: {
          paid_flag_hours?: number
          period_key: string
          user_id: string
        }
        Update: {
          paid_flag_hours?: number
          period_key?: string
          user_id?: string
        }
        Relationships: []
      }
      user_settings: {
        Row: {
          default_labor_type: string | null
          goal_hours: number
          is_admin: boolean
          period_overrides: Json
          reference_hourly_rate: number | null
          ro_template: Json | null
          split_day: number
          tag_colors: Json
          timer_accumulated: number
          timer_ro_id: string | null
          timer_start_time: number | null
          updated_at: string
          user_id: string
        }
        Insert: {
          default_labor_type?: string | null
          goal_hours?: number
          is_admin?: boolean
          period_overrides?: Json
          reference_hourly_rate?: number | null
          ro_template?: Json | null
          split_day?: number
          tag_colors?: Json
          timer_accumulated?: number
          timer_ro_id?: string | null
          timer_start_time?: number | null
          updated_at?: string
          user_id: string
        }
        Update: {
          default_labor_type?: string | null
          goal_hours?: number
          is_admin?: boolean
          period_overrides?: Json
          reference_hourly_rate?: number | null
          ro_template?: Json | null
          split_day?: number
          tag_colors?: Json
          timer_accumulated?: number
          timer_ro_id?: string | null
          timer_start_time?: number | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      work_schedules: {
        Row: {
          anchor_monday: string
          created_at: string
          effective_from: string
          id: string
          rotation_weeks: number
          user_id: string
          weeks: Json
        }
        Insert: {
          anchor_monday: string
          created_at?: string
          effective_from: string
          id?: string
          rotation_weeks?: number
          user_id: string
          weeks: Json
        }
        Update: {
          anchor_monday?: string
          created_at?: string
          effective_from?: string
          id?: string
          rotation_weeks?: number
          user_id?: string
          weeks?: Json
        }
        Relationships: []
      }
      work_shift_overrides: {
        Row: {
          created_at: string
          date: string
          shift: Json
          user_id: string
        }
        Insert: {
          created_at?: string
          date: string
          shift: Json
          user_id: string
        }
        Update: {
          created_at?: string
          date?: string
          shift?: Json
          user_id?: string
        }
        Relationships: []
      }
      confirmed_zero_days: {
        Row: {
          created_at: string
          date: string
          user_id: string
        }
        Insert: {
          created_at?: string
          date: string
          user_id: string
        }
        Update: {
          created_at?: string
          date?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      reorder_op_codes: {
        Args: {
          updates: Json
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const

