/**
 * Seed the STAGING Supabase project with two test accounts and realistic data.
 *
 *   npx --yes tsx scripts/seed-staging.ts
 *
 * WHY THIS EXISTS
 * Local dev used to point at prod, and fixture mode throws every write away, so
 * no write flow (log an RO, dispute, import) could be exercised safely anywhere.
 * Staging is a real database you're allowed to break; this script puts it back.
 *
 * WHAT IT DOES — safe to re-run, that's the point
 *   1. Deletes the two test users if they exist. Every user-data table cascades
 *      on auth.users delete, so that wipes all their rows too.
 *   2. Recreates them (email pre-confirmed, so nothing is ever sent).
 *   3. Replaces the 6 default op codes the sign-up trigger creates with the
 *      fixture set, then loads the fixture world for each account.
 *
 *   tech-a  — the full fixture world (~90 ROs over ~10 weeks), is_admin = true
 *             so /admin pages are testable.
 *   tech-b  — the last two weeks of it, not admin. Exists for the two-account
 *             RLS check: sign in as B, you must never see A's ROs.
 *
 * DATES FOLLOW TODAY
 * The fixture is frozen in Jan–Mar 2026. Every date in it is shifted forward by
 * whole weeks (so Mondays stay Mondays and the Saturday "unpaired day" stays a
 * Saturday) until the last working day lands on or before today. The data ends
 * somewhere in the last 7 days; re-run to bring it current.
 *
 * IT CANNOT TOUCH PROD
 * The URL is STAGING_URL (src/lib/supabase/environments.ts), never read from the environment, and
 * the secret key is only valid for that project. There is no flag to point it
 * anywhere else, on purpose.
 *
 * Secrets: .env.staging.local (gitignored). Needs SUPABASE_SECRET_KEY.
 * STAGING_TEST_PASSWORD is generated and appended on the first run.
 */
import { randomBytes, randomUUID } from "node:crypto";
import { appendFileSync, readFileSync } from "node:fs";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import {
  dailyClockHours,
  entries,
  laborRates,
  opCodes,
  portfolioSnapshots,
  userSettings,
  workSchedules,
} from "../src/lib/fixtures/data";
import { FIXTURE_NOW_ISO } from "../src/lib/fixtures/enabled";
import { STAGING_URL as URL } from "../src/lib/supabase/environments";
const ENV_FILE = ".env.staging.local";

const ACCOUNTS = [
  { email: "tech-a@frt-staging.test", admin: true, recentDaysOnly: null },
  { email: "tech-b@frt-staging.test", admin: false, recentDaysOnly: 14 },
] as const;

// ── env ─────────────────────────────────────────────────────────────────────
// Parsed literally (split on the first "="), never shell-sourced: the DB
// password in this file contains characters a shell would interpret.
function readEnv(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of readFileSync(ENV_FILE, "utf8").split(/\r?\n/)) {
    if (!line || line.startsWith("#") || !line.includes("=")) continue;
    const i = line.indexOf("=");
    out[line.slice(0, i)] = line.slice(i + 1);
  }
  return out;
}

const env = readEnv();
const SECRET = env.SUPABASE_SECRET_KEY;
if (!SECRET?.startsWith("sb_secret_")) {
  throw new Error(`SUPABASE_SECRET_KEY missing or malformed in ${ENV_FILE}`);
}
let PASSWORD = env.STAGING_TEST_PASSWORD;
if (!PASSWORD) {
  PASSWORD = randomBytes(18).toString("base64url");
  appendFileSync(
    ENV_FILE,
    `\n# Password for the seeded staging test accounts (tech-a / tech-b). Generated by seed-staging.ts.\nSTAGING_TEST_PASSWORD=${PASSWORD}\n`,
  );
  console.log(`Generated a test-account password and saved it to ${ENV_FILE}`);
}

// ── date shift ──────────────────────────────────────────────────────────────
const DAY = 86_400_000;
const lastFixtureDay = Math.max(
  ...entries.map((e) => Date.parse(`${(e as Record<string, unknown>).date as string}T00:00:00Z`)),
);
const todayUtc = Date.parse(new Date().toISOString().slice(0, 10) + "T00:00:00Z");
const SHIFT_MS = Math.floor((todayUtc - lastFixtureDay) / (7 * DAY)) * 7 * DAY;

const DATE_RE = /^\d{4}-\d{2}-\d{2}(T.*)?$/;
function shiftDateString(s: string): string {
  const isDateOnly = s.length === 10;
  const t = Date.parse(isDateOnly ? `${s}T00:00:00Z` : s) + SHIFT_MS;
  return isDateOnly ? new Date(t).toISOString().slice(0, 10) : new Date(t).toISOString();
}
/** Deep-copies a value, moving every date / ISO timestamp string by SHIFT_MS. */
function shifted<T>(v: T): T {
  if (typeof v === "string") return (DATE_RE.test(v) ? shiftDateString(v) : v) as T;
  if (Array.isArray(v)) return v.map(shifted) as T;
  if (v && typeof v === "object") {
    return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, shifted(x)])) as T;
  }
  return v;
}
const NOW = shiftDateString(FIXTURE_NOW_ISO);

// ── helpers ─────────────────────────────────────────────────────────────────
/** Copy of `row` without `keys` — fixture ids/owners are replaced, never reused. */
function omit<T extends Record<string, unknown>, K extends keyof T>(row: T, ...keys: K[]): Omit<T, K> {
  const out = { ...row };
  for (const k of keys) delete out[k];
  return out;
}

async function must<T>(label: string, p: PromiseLike<{ data: T; error: unknown }>): Promise<T> {
  const { data, error } = await p;
  if (error) throw new Error(`${label}: ${JSON.stringify(error)}`);
  return data;
}

async function findUserId(db: SupabaseClient, email: string): Promise<string | null> {
  for (let page = 1; ; page++) {
    const { data, error } = await db.auth.admin.listUsers({ page, perPage: 200 });
    if (error) throw new Error(`listUsers: ${error.message}`);
    const hit = data.users.find((u) => u.email === email);
    if (hit) return hit.id;
    if (data.users.length < 200) return null;
  }
}

// ── seed one account ────────────────────────────────────────────────────────
async function seedAccount(db: SupabaseClient, acct: (typeof ACCOUNTS)[number]) {
  const existing = await findUserId(db, acct.email);
  if (existing) {
    // Deliberately the plain admin delete, cascade and all: it's the same path
    // account deletion takes, so every reseed re-proves it. It failed for any
    // user with RO lines until 20261007000000_recompute_flag_hours_definer.
    const { error } = await db.auth.admin.deleteUser(existing);
    if (error) throw new Error(`deleteUser ${acct.email}: ${error.message}`);
  }
  const { data: created, error: createErr } = await db.auth.admin.createUser({
    email: acct.email,
    password: PASSWORD,
    email_confirm: true,
  });
  if (createErr || !created.user) throw new Error(`createUser ${acct.email}: ${createErr?.message}`);
  const uid = created.user.id;

  // The sign-up trigger (handle_new_user) inserted user_settings + 6 default op
  // codes. Swap the codes for the fixture set; settings are updated below.
  await must("clear default op codes", db.from("op_codes").delete().eq("user_id", uid));

  const opIdMap = new Map<string, string>();
  const opRows = opCodes.map((o) => {
    const newId = randomUUID();
    opIdMap.set(o.id, newId);
    return { ...shifted(o), id: newId, user_id: uid };
  });
  await must("op_codes", db.from("op_codes").insert(opRows));

  const cutoff = acct.recentDaysOnly
    ? new Date(todayUtc - acct.recentDaysOnly * DAY).toISOString().slice(0, 10)
    : null;

  const entryRows: Record<string, unknown>[] = [];
  const lineRows: Record<string, unknown>[] = [];
  for (const e of entries) {
    const { entry_op_codes: lines, ...row } = shifted(e) as Record<string, unknown> & {
      entry_op_codes: Record<string, unknown>[];
    };
    if (cutoff && (row.date as string) < cutoff) continue;
    const entryId = randomUUID();
    entryRows.push({ ...row, id: entryId, user_id: uid });
    for (const l of lines) {
      lineRows.push({
        ...omit(l, "id"),
        // The visual fixture gives its comeback lines the op code's book hours,
        // which entry_op_codes_comeback_zero_flag refuses (a comeback pays 0).
        // Follow the database, not the fixture. Fixture fix is a follow-up: it
        // moves totals on several visual baselines.
        ...(l.is_comeback ? { flag_hours: 0 } : {}),
        entry_id: entryId,
        op_code_id: l.op_code_id ? opIdMap.get(l.op_code_id as string) ?? null : null,
      });
    }
  }
  // Entries before lines: the entry_op_codes trigger recomputes the parent's
  // flag_hours on every line insert, so the parent must already exist.
  for (let i = 0; i < entryRows.length; i += 200) {
    await must("entries", db.from("entries").insert(entryRows.slice(i, i + 200)));
  }
  for (let i = 0; i < lineRows.length; i += 200) {
    await must("entry_op_codes", db.from("entry_op_codes").insert(lineRows.slice(i, i + 200)));
  }

  const clock = dailyClockHours
    .map((c) => ({ ...shifted(c), user_id: uid }))
    .filter((c) => !cutoff || c.date >= cutoff);
  await must("daily_clock_hours", db.from("daily_clock_hours").insert(clock));

  await must(
    "work_schedules",
    db.from("work_schedules").insert(workSchedules.map((w) => ({ ...omit(shifted(w), "id"), user_id: uid }))),
  );
  await must(
    "labor_rates",
    db.from("labor_rates").insert(laborRates.map((r) => ({ ...omit(shifted(r), "id"), user_id: uid }))),
  );
  if (!cutoff) {
    // Milestone sheets only make sense on the account that crossed 10/25/50 ROs.
    await must(
      "portfolio_snapshots",
      db
        .from("portfolio_snapshots")
        .insert(portfolioSnapshots.map((s) => ({ ...omit(shifted(s), "id"), user_id: uid }))),
    );
  }

  const settings = omit(shifted(userSettings), "user_id");
  await must(
    "user_settings",
    db
      .from("user_settings")
      .update({ ...settings, is_admin: acct.admin, share_labor_times: true })
      .eq("user_id", uid),
  );

  // Two things the visual fixture leaves empty but a tester will want to see
  // populated: a spiff on the books and a day off in the current stretch.
  const lastDay = entryRows.map((e) => e.date as string).sort().at(-1)!;
  const dayBefore = (d: string, n: number) =>
    new Date(Date.parse(`${d}T00:00:00Z`) - n * DAY).toISOString().slice(0, 10);
  await must(
    "bonuses",
    db.from("bonuses").insert({
      user_id: uid,
      date: dayBefore(lastDay, 2),
      category: "spiff",
      amount: 25,
      note: "Seeded: alignment spiff",
      created_at: NOW,
      updated_at: NOW,
    }),
  );
  await must(
    "days_off",
    db.from("days_off").insert({
      user_id: uid,
      start_date: dayBefore(lastDay, 10),
      end_date: dayBefore(lastDay, 10),
      created_at: NOW,
    }),
  );

  return { uid, ros: entryRows.length, lines: lineRows.length, lastDay };
}

// ── main ────────────────────────────────────────────────────────────────────
async function main() {
  const db = createClient(URL, SECRET!, { auth: { persistSession: false, autoRefreshToken: false } });
  console.log(`Seeding STAGING ${URL} (dates shifted +${SHIFT_MS / (7 * DAY)} weeks)`);
  for (const acct of ACCOUNTS) {
    const r = await seedAccount(db, acct);
    console.log(
      `  ${acct.email}${acct.admin ? " (admin)" : ""}: ${r.ros} ROs, ${r.lines} lines, data through ${r.lastDay}`,
    );
  }
  console.log(`Done. Sign in with either email; password is STAGING_TEST_PASSWORD in ${ENV_FILE}.`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
